### ISSUE TITLE
periodic functions not working

### ISSUE THREAD

**Issue by dragonruler1000** [frc538/2024-game#14]
cant get a smart dashboard message to show up on shuffel board. havent tryed this outside of simulation but wyatt cant get that to work either.

**Comment by dragonruler1000** [comment]
turns out my problem is driver station is not sinced up with robot simulation. it is saying no robot code currently running butis showing that it can detect the robot code and can comunicate with the robot.

**Comment by minecraftchest1** [comment]
@dragonruler1000 Can this be closed?
