### ISSUE TITLE
Use Limelight helper functions

### ISSUE THREAD

**Issue by npatrick04** [frc538/2024-game#19]
LimelightHelpers provides a utility interface that should replace the full calls.

e.g.

FROM:
NetworkTableInstance.getDefault().getTable("limelight").getEntry("tv").getDouble(0);

TO:
LimelightHelpers.getTV("limelight");

**Comment by minecraftchest1** [comment]
Fixed in 312b5db2e27ecd8c7ebd32b8429234b9f895cf65
