### ISSUE TITLE
Improve names of constants.

### ISSUE THREAD

**Issue by minecraftchest1** [frc538/2024-game#29]
these names should have units on them (_e.g._, `FrontLeftDriveWheel_Position_X_meters` if the unit is meters)

_Originally posted by @drewwhis in https://github.com/frc538/2024-game/pull/17#discussion_r1495219562_

**Comment by minecraftchest1** [comment]
you may want to reconsider how you have your `Constants.CANSparkMaxID` values named, but I wouldn't consider it a blocker here.

_Originally posted by @drewwhis in https://github.com/frc538/2024-game/pull/17#discussion_r1495222238_

**Comment by minecraftchest1** [comment]
> ```
>           these names should have units on them (_e.g._, `FrontLeftDriveWheel_Position_X_meters` if the unit is meters)
> ```
> 
> _Originally posted by @drewwhis in [#17 (comment)](https://github.com/frc538/2024-game/pull/17#discussion_r1495219562)_

Fixed in [1b6187](https://github.com/frc538/2024-game/commit/41b61870f53e31b133cc3bb5514215b01744b064). Fixed failed build in [5ad3dd1](https://github.com/frc538/2024-game/pull/17/commits/5ad3dd16488391f28e6316e58cf39b6e8d5a5cbb)

**Comment by dragonruler1000** [comment]
aaaa8e9dd81407a04166aef3598da200a98dcf98 renamed CANSparkMaxID to CANIDs
