### ISSUE TITLE
Add eject method.

### ISSUE THREAD

**Issue by minecraftchest1** [frc538/2024-game#30]
you've got an `intake` method, but you may want to add an `eject` method (to spit out a piece that was mistakenly brought in, for example) and a `stop` method (in case you need more granular control). I wouldn't hold this up for that though - something to consider.

_Originally posted by @drewwhis in https://github.com/frc538/2024-game/pull/17#discussion_r1495221733_

**Comment by dragonruler1000** [comment]
21582bc9bf5c181095fe051b42bb1b234282b069 added an eject method
