### ISSUE TITLE
Consider improvements to input handeling.

### ISSUE THREAD

**Issue by minecraftchest1** [frc538/2024-game#32]
you may want to consider `onFalse` vs. `whileTrue` as well as `Commands.run` vs. `Commands.startEnd` - not necessarily that this isn't right - you may find better options with those when testing gets here. but don't let this block you.

_Originally posted by @drewwhis in https://github.com/frc538/2024-game/pull/17#discussion_r1495224664_

**Comment by dragonruler1000** [comment]
fixed in commit faabfd8fc1e226301b06788203f25396bc179ad6
