### ISSUE TITLE
Set pickup to 0 when launching.

### ISSUE THREAD

**Issue by minecraftchest1** [frc538/2024-game#33]
you probably want to set `pickup` to run at `0` speed with this method, since the mechanism should only be running one set of motors at a time, based on my reading

_Originally posted by @drewwhis in https://github.com/frc538/2024-game/pull/17#discussion_r1495222925_

**Comment by dragonruler1000** [comment]
aaaa8e9dd81407a04166aef3598da200a98dcf98 fixed this
